### PR TITLE
Support xpress

### PR DESCRIPTION
**Pull request by spoorendonk**
Addressing #129

### CODE REVIEW

**Comment by tkralphs** [comment]
Oh, whoops, I just pushed a branch for this. Well, maybe you can look at what I have and see if there are any updates to this PR. Since it's labelled a work-in-progress, I assume it's not done yet. You probably want to add test support for Xpress. I just fixed what seemed to be a bug in the Makefile for the unit test that should now allow all solvers that are available to be tested, one by one. I had thought that was working before,

**Comment by spoorendonk** [comment]
https://github.com/coin-or/Osi/pull/141

**Comment by spoorendonk** [comment]
It fails the same test as https://github.com/coin-or/Dip/pull/120 both related to a SYMPHONY test?

**Comment by tkralphs** [comment]
Argh, I've been trying to replicate that failure and haven't been able to. Yeah, seems to be a SYMPHONY thing, likely to some kind of memory corruption, since it fails kind of randomly. In fact, tests passed on d85e13e, just one commit earlier. It's also failing on Windows here and OS X in #120. I'll try with valgrind and see if I can turn up anything.

 Other than that, changes look good!

**Pull request merged**
